{"status": "broken", "name": "Returning label predicate expression", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "MatchAcceptance2"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486067667, "historyId": "ee8d0b494253872e1fbdab6f942d9b43", "start": 1578486067462, "steps": [{"status": "passed", "start": 1578486067465, "stop": 1578486067657, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486067658, "stop": 1578486067661, "name": "And having executed", "attachments": [{"source": "e5b6ee4e-fe6e-49f8-b74c-9da6ff154d91-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486067661, "stop": 1578486067663, "name": "When executing query", "attachments": [{"source": "a0a9f28a-f7bd-4b72-9210-cc30f4e60745-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "4615005e-e490-4b13-af5c-36774684c05e-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486067666, "start": 1578486067665, "statusDetails": {"message": "ResponseError: RedisGraph does not currently support has labels\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486067667, "stop": 1578486067667, "name": "And no side effects"}], "statusDetails": {"message": "ResponseError: RedisGraph does not currently support has labels\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "ef821699-813e-4357-ae61-09452291a329"}