{"status": "broken", "name": "Using a variable-length pattern comprehension in a WITH", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "PatternComprehension"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486116028, "historyId": "7e057a4d4e36920850f4c62cd06996ff", "start": 1578486115805, "steps": [{"status": "passed", "start": 1578486115805, "stop": 1578486116020, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486116020, "stop": 1578486116023, "name": "And having executed", "attachments": [{"source": "29dc4b13-2bfc-4096-a88b-b768f94ea24d-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486116024, "stop": 1578486116026, "name": "When executing query", "attachments": [{"source": "de799f6f-8b34-4151-9601-5d5bf1b787ba-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "51825a3b-c53d-4e7f-9ea5-125d0a5a8760-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486116028, "start": 1578486116026, "statusDetails": {"message": "ResponseError: RedisGraph does not currently support pattern comprehension\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486116028, "stop": 1578486116028, "name": "And no side effects"}], "statusDetails": {"message": "ResponseError: RedisGraph does not currently support pattern comprehension\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "6d8376bc-ba67-4726-bea1-4d9fbbeb0d04"}