{"status": "broken", "name": "Ignoring intermediate whitespace 1", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "LabelsAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486031757, "historyId": "a07b91e19a96f9ee49e23341b0054038", "start": 1578486031544, "steps": [{"status": "passed", "start": 1578486031546, "stop": 1578486031748, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486031748, "stop": 1578486031751, "name": "And having executed", "attachments": [{"source": "2bd61b2a-b463-481b-a852-f7bd409d9fb7-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486031751, "stop": 1578486031754, "name": "When executing query", "attachments": [{"source": "3f9fb734-17ea-46c6-b840-ba4ca664f930-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "3e8cfb90-6d4a-432c-aaf0-edf77c2cbbff-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486031756, "start": 1578486031754, "statusDetails": {"message": "ResponseError: RedisGraph does not currently support set labels\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486031756, "stop": 1578486031757, "name": "And the side effects should be", "attachments": [{"source": "465ab989-cf69-45dd-ac87-e5a12a7560b0-attachment.csv", "type": "text/csv", "name": ".table"}]}], "statusDetails": {"message": "ResponseError: RedisGraph does not currently support set labels\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "a52bbeae-e0e7-470d-b206-b2a52a2f6bec"}