{"status": "failed", "name": "Failing when using undefined variable in pattern", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "MiscellaneousErrorAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486098988, "historyId": "6760e14009beff2c88e185a37e5e38a1", "start": 1578486098860, "steps": [{"status": "passed", "start": 1578486098862, "stop": 1578486098982, "name": "Given any graph"}, {"status": "passed", "start": 1578486098983, "stop": 1578486098986, "name": "When executing query", "attachments": [{"source": "8c0d6ad0-d083-4de7-839f-82a400f8d10f-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "failed", "start": 1578486098986, "stop": 1578486098987, "name": "Then a SyntaxError should be raised at compile time: UndefinedVariable", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 116, in step_impl\n    assert exception != None\n"}}], "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 116, in step_impl\n    assert exception != None\n"}, "uuid": "b3278a11-3e4f-44d5-9b8f-89196317fd60"}