{"status": "broken", "name": "Execute n['name'] in update queries", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "ExpressionAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486018025, "historyId": "c224f3ff35729c6d4e9711c0f75074f8", "start": 1578486017801, "steps": [{"status": "passed", "start": 1578486017803, "stop": 1578486018018, "name": "Given any graph"}, {"status": "passed", "start": 1578486018018, "stop": 1578486018021, "name": "When executing query", "attachments": [{"source": "4bdf8540-60b8-40db-97c8-ee4599312d71-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "c3b7f075-00a0-4933-afac-284bdf802655-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486018023, "start": 1578486018022, "statusDetails": {"message": "ResponseError: Type mismatch: expected List but was Node\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486018024, "stop": 1578486018025, "name": "And the side effects should be", "attachments": [{"source": "ab3eb791-55a3-4240-8153-71eb1c4e5701-attachment.csv", "type": "text/csv", "name": ".table"}]}], "statusDetails": {"message": "ResponseError: Type mismatch: expected List but was Node\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "a2ab26d2-a972-48c7-a4f6-5fed20971f1b"}