{"status": "broken", "name": "Handling non-string operands for ENDS WITH", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "StartsWithAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486153914, "historyId": "b4155d488914bfdd30f21b62fe1ae0ff", "start": 1578486153686, "steps": [{"status": "passed", "start": 1578486153686, "stop": 1578486153905, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486153906, "stop": 1578486153910, "name": "And having executed", "attachments": [{"source": "badafbaa-0968-4c27-843c-58a884354976-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486153910, "stop": 1578486153913, "name": "When executing query", "attachments": [{"source": "3aeaf22d-9f2c-4576-abcd-19d6776318d1-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "5ab10c26-0edf-4934-a1e7-7310398a0d20-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486153914, "start": 1578486153913, "statusDetails": {"message": "ResponseError: Maps are not currently supported outside of node and relation patterns.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486153914, "stop": 1578486153914, "name": "And no side effects"}], "statusDetails": {"message": "ResponseError: Maps are not currently supported outside of node and relation patterns.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "f4c202ce-d65b-4c88-a1e9-7476c1488d83"}