{"status": "failed", "name": "Merge must properly handle multiple labels", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "MergeNodeAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486090247, "historyId": "60abdb3b6c0a7209a510e96880c11c1c", "start": 1578486090046, "steps": [{"status": "passed", "start": 1578486090046, "stop": 1578486090244, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486090244, "stop": 1578486090245, "name": "And having executed", "attachments": [{"source": "7b31e36d-20ca-4fda-b543-54a9bbbe3d53-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486090245, "stop": 1578486090246, "name": "When executing query", "attachments": [{"source": "4ab51c91-bbb1-40be-b83c-b2ee38a2b86b-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "failed", "attachments": [{"source": "36ae007e-37ff-44db-be7d-91b8a5d3c2fd-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486090246, "start": 1578486090246, "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 87, in step_impl\n    assertions.assert_resultsets_equals(resultset, context.table)\n  File \"/home/laptop-linux/dev/redis/graph/tests/tck/features/steps/../../utils/assertions.py\", line 218, in assert_resultsets_equals\n    assert actualCtr == expectedCtr\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486090246, "stop": 1578486090247, "name": "And the side effects should be", "attachments": [{"source": "d99c15ad-4c85-410c-a205-bc23fb737b6c-attachment.csv", "type": "text/csv", "name": ".table"}]}], "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 87, in step_impl\n    assertions.assert_resultsets_equals(resultset, context.table)\n  File \"/home/laptop-linux/dev/redis/graph/tests/tck/features/steps/../../utils/assertions.py\", line 218, in assert_resultsets_equals\n    assert actualCtr == expectedCtr\n"}, "uuid": "7eb1003c-692b-4e10-b486-c224f0a5be5f"}